---
- name: Create users
  hosts: web-server
  become: true
  vars_files:
    - vars2.yaml 
  tasks:
    - name: Show users
      debug:
        msg: "{{ item.value }}"
      with_items: "{{ users }}"