---
- name: Test Custom Facts
  hosts: webserver1
  tasks:
    - name: Get Web details
      debug:
        msg: "{{ ansible_local.web.web_details.web_port }}"
      when: ansible_local.web.business.criticality is defined
