---
- name: Using Secrets in Playbook
  hosts: webserver1
  become: true
  vars_files:
    -  user-passwd.yaml
  tasks:
    - name: Create User
      user:
        name: "{{ username }}"
        password: "{{ passwd | password_hash('sha256') }}"
